# Generated by Django 5.1.9 on 2025-06-13 14:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0004_alter_options_ordering_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('image_link', models.URLField(unique=True, verbose_name='image link')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('link', models.URLField(unique=True, verbose_name='social media link')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='sites.site', verbose_name='related site')),
            ],
            options={
                'verbose_name': 'About',
            },
        ),
    ]
